"""Node type definitions for all 53 Fallout 4 behavior graph node types.

Each entry maps a nodeTypeID (0-52) to its class name, XML class, properties,
and port definitions. This is the single source of truth for the node type system.
"""

# Port definition: list of (name, multi_connect) tuples
# multi_connect=True means multiple connections allowed on that port

NODE_TYPE_DEFINITIONS = {
    0: {
        "class_name": "hkRootLevelContainer",
        "xml_class": "hkRootLevelContainer",
        "category": "Root",
        "signature": "0x2772c11e",
        "properties": {
            "className": ("str", "hkbBehaviorGraph"),
        },
        "output_ports": [("variant", False)],
        "input_ports": [("in", False)],
    },
    1: {
        "class_name": "hkbBehaviorGraph",
        "xml_class": "hkbBehaviorGraph",
        "category": "Root",
        "signature": "0xfdedb83b",
        "properties": {
            "nodeName": ("str", ""),
            "className": ("str", "hkbBehaviorGraph"),
        },
        "output_ports": [("rootGenerator", False)],
        "input_ports": [("in", False)],
    },
    2: {
        "class_name": "hkbBehaviorGraphData",
        "xml_class": "hkbBehaviorGraphData",
        "category": "Metadata",
        "signature": "0x907a8222",
        "properties": {},
        "output_ports": [],
        "input_ports": [],
        "metadata_only": True,
    },
    3: {
        "class_name": "hkbVariableValueSet",
        "xml_class": "hkbVariableValueSet",
        "category": "Metadata",
        "signature": "0xeb5f7e25",
        "properties": {},
        "output_ports": [],
        "input_ports": [],
        "metadata_only": True,
    },
    4: {
        "class_name": "hkbBehaviorGraphStringData",
        "xml_class": "hkbBehaviorGraphStringData",
        "category": "Metadata",
        "signature": "0x1bd27f38",
        "properties": {},
        "output_ports": [],
        "input_ports": [],
        "metadata_only": True,
    },
    5: {
        "class_name": "hkbStateMachine",
        "xml_class": "hkbStateMachine",
        "category": "hkbS",
        "signature": "0xa5896bcf",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "eventId": ("int", -1),
            "payload": ("int", -1),
            "startStateId": ("int", 0),
            "randomTransitionEventId": ("int", -1),
            "transitionToNextHigherStateEventId": ("int", -1),
            "transitionToNextLowerStateEventId": ("int", -1),
            "syncVariableIndex": ("int", -1),
            "wrapAroundStateId": ("bool", False),
            "startStateMode": ("str", "START_STATE_MODE_DEFAULT"),
            "selfTransitionMode": ("str", "SELF_TRANSITION_MODE_NO_TRANSITION"),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("states", True),
            ("wildcardTransitions", False),
        ],
        "input_ports": [("in", False)],
    },
    6: {
        "class_name": "hkbStateMachineStateInfo",
        "xml_class": "hkbStateMachineStateInfo",
        "category": "hkbS",
        "signature": "0x39d76713",
        "properties": {
            "nodeName": ("str", ""),
            "stateId": ("int", 0),
            "probability": ("str", "1.000000"),
            "enable": ("bool", True),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("enterNotifyEvents", False),
            ("exitNotifyEvents", False),
            ("transitions", False),
            ("generator", False),
        ],
        "input_ports": [("in", False)],
    },
    7: {
        "class_name": "hkbStateMachineTransitionInfoArray",
        "xml_class": "hkbStateMachineTransitionInfoArray",
        "category": "hkbS",
        "signature": "0x704a19af",
        "properties": {
            "transitionArray": ("list", []),
        },
        "output_ports": [],
        "input_ports": [("in", False)],
    },
    8: {
        "class_name": "hkbStateMachineEventPropertyArray",
        "xml_class": "hkbStateMachineEventPropertyArray",
        "category": "hkbS",
        "signature": "0x71957c2d",
        "properties": {
            "eventsArray": ("list", []),
        },
        "output_ports": [],
        "input_ports": [("in", False)],
    },
    9: {
        "class_name": "hkbModifierGenerator",
        "xml_class": "hkbModifierGenerator",
        "category": "hkbM",
        "signature": "0xc499fc9e",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("modifier", False),
            ("generator", False),
        ],
        "input_ports": [("in", False)],
    },
    10: {
        "class_name": "hkbModifierList",
        "xml_class": "hkbModifierList",
        "category": "hkbM",
        "signature": "0xded564c",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("modifiers", True),
        ],
        "input_ports": [("in", False)],
    },
    11: {
        "class_name": "hkbGetUpModifier",
        "xml_class": "hkbGetUpModifier",
        "category": "hkbG",
        "signature": "0x84519a60",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "groundNormal": ("str", "(0.0 0.0 1.0 0.0)"),
            "duration": ("str", "0.000000"),
            "alignWithGroundDuration": ("str", "0.000000"),
            "rootBoneIndex": ("int", -1),
            "otherBoneIndex": ("int", -1),
            "anotherBoneIndex": ("int", -1),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
    },
    12: {
        "class_name": "hkbKeyframeBonesModifier",
        "xml_class": "hkbKeyframeBonesModifier",
        "category": "Root",
        "signature": "0x4e45d0f7",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("keyframedBonesList", False),
        ],
        "input_ports": [("in", False)],
    },
    13: {
        "class_name": "hkbBoneIndexArray",
        "xml_class": "hkbBoneIndexArray",
        "category": "hkbB",
        "signature": "0x3d26f425",
        "properties": {
            "boneIndices": ("list", []),
        },
        "output_ports": [],
        "input_ports": [("in", False)],
    },
    14: {
        "class_name": "hkbBoneWeightArray",
        "xml_class": "hkbBoneWeightArray",
        "category": "hkbB",
        "signature": "0x2c9b5751",
        "properties": {
            "boneWeights": ("list", []),
        },
        "output_ports": [],
        "input_ports": [("in", False)],
    },
    15: {
        "class_name": "hkbRigidBodyRagdollControlsModifier",
        "xml_class": "hkbRigidBodyRagdollControlsModifier",
        "category": "hkbR",
        "signature": "0xb7c3fe7d",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "hierarchyGain": ("str", "0.170000"),
            "velocityDamping": ("str", "0.000000"),
            "accelerationGain": ("str", "1.000000"),
            "velocityGain": ("str", "0.600000"),
            "positionGain": ("str", "0.050000"),
            "positionMaxLinearVelocity": ("str", "1.400000"),
            "positionMaxAngularVelocity": ("str", "1.800000"),
            "snapGain": ("str", "0.100000"),
            "snapMaxLinearVelocity": ("str", "0.300000"),
            "snapMaxAngularVelocity": ("str", "0.300000"),
            "snapMaxLinearDistance": ("str", "0.030000"),
            "snapMaxAngularDistance": ("str", "0.100000"),
            "durationToBlend": ("str", "0.000000"),
            "animationBlendFraction": ("str", "0.000000"),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("bones", False),
        ],
        "input_ports": [("in", False)],
    },
    16: {
        "class_name": "BSIsActiveModifier",
        "xml_class": "BSIsActiveModifier",
        "category": "BS",
        "signature": "0x5bf1f5cf",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "bIsActiveArray": ("list", [False] * 10),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
    },
    17: {
        "class_name": "hkbVariableBindingSet",
        "xml_class": "hkbVariableBindingSet",
        "category": "Root",
        "signature": "0xe942f339",
        "properties": {
            "bindingArray": ("list", []),
            "indexOfBindingToEnable": ("int", -1),
        },
        "output_ports": [],
        "input_ports": [("in", False)],
    },
    18: {
        "class_name": "hkbManualSelectorGenerator",
        "xml_class": "hkbManualSelectorGenerator",
        "category": "hkbM",
        "signature": "0xeed8d5cd",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "selectedGeneratorIndex": ("int", 0),
            "selectedIndexCanChangeAfterActivate": ("bool", False),
            "generatorChangedTransitionEffect": ("int", -1),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("generators", True),
            ("indexSelector", False),
        ],
        "input_ports": [("in", False)],
    },
    19: {
        "class_name": "BSModifyOnceModifier",
        "xml_class": "BSModifyOnceModifier",
        "category": "BS",
        "signature": "0x14f075d2",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("pOnActivateModifier", False),
            ("pOnDeactivateModifier", False),
        ],
        "input_ports": [("in", False)],
    },
    20: {
        "class_name": "hkbEvaluateExpressionModifier",
        "xml_class": "hkbEvaluateExpressionModifier",
        "category": "hkbE",
        "signature": "0x4a3ac449",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("expressions", False),
        ],
        "input_ports": [("in", False)],
    },
    21: {
        "class_name": "hkbExpressionDataArray",
        "xml_class": "hkbExpressionDataArray",
        "category": "hkbE",
        "signature": "0x1ebfc6d7",
        "properties": {
            "expressionArray": ("list", []),
        },
        "output_ports": [],
        "input_ports": [("in", False)],
    },
    22: {
        "class_name": "hkbPoseMatchingGenerator",
        "xml_class": "hkbPoseMatchingGenerator",
        "category": "hkbP",
        "signature": "0xb2aa2982",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "blendParameter": ("str", "0.000000"),
            "blendSpeed": ("str", "1.000000"),
            "minSpeedToSwitch": ("str", "0.200000"),
            "startPlayingEventId": ("int", -1),
            "startMatchingEventId": ("int", -1),
            "rootBoneIndex": ("int", -1),
            "otherBoneIndex": ("int", -1),
            "anotherBoneIndex": ("int", -1),
            "pelvisIndex": ("int", -1),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("children", True),
        ],
        "input_ports": [("in", False)],
    },
    23: {
        "class_name": "hkbBlenderGenerator",
        "xml_class": "hkbBlenderGenerator",
        "category": "hkbB",
        "signature": "0xce45c088",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "referencePoseWeightThreshold": ("str", "0.0"),
            "blendParameter": ("str", "0.000000"),
            "minCyclicBlendParameter": ("str", "0.000000"),
            "maxCyclicBlendParameter": ("str", "1.000000"),
            "indexOfSyncMasterChild": ("int", 65535),
            "flagsIndex": ("int", 0),
            "subtractLastChild": ("bool", False),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("children", True),
        ],
        "input_ports": [("in", False)],
    },
    24: {
        "class_name": "hkbBlenderGeneratorChild",
        "xml_class": "hkbBlenderGeneratorChild",
        "category": "hkbB",
        "signature": "0xb35bbfd3",
        "properties": {
            "weight": ("str", "1.000000"),
            "worldFromModelWeight": ("str", "1.000000"),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("generator", False),
            ("boneWeights", False),
        ],
        "input_ports": [("in", False)],
    },
    25: {
        "class_name": "hkbClipGenerator",
        "xml_class": "hkbClipGenerator",
        "category": "hkbC",
        "signature": "0xd4cc9f6",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "animationName": ("str", ""),
            "cropStartAmountLocalTime": ("str", "0.000000"),
            "cropEndAmountLocalTime": ("str", "0.000000"),
            "startTime": ("str", "0.000000"),
            "playbackSpeed": ("str", "1.000000"),
            "enforcedDuration": ("str", "0.000000"),
            "userControlledTimeFraction": ("str", "0.000000"),
            "mode": ("int", 0),
            "flagsIndex": ("int", 0),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("triggers", False),
        ],
        "input_ports": [("in", False)],
    },
    26: {
        "class_name": "hkbClipTriggerArray",
        "xml_class": "hkbClipTriggerArray",
        "category": "hkbC",
        "signature": "0xf757cd66",
        "properties": {
            "triggersArray": ("list", []),
        },
        "output_ports": [],
        "input_ports": [("in", False)],
    },
    27: {
        "class_name": "hkbBlendingTransitionEffect",
        "xml_class": "hkbBlendingTransitionEffect",
        "category": "Metadata",
        "signature": "0x14e54c5c",
        "properties": {},
        "output_ports": [],
        "input_ports": [],
        "metadata_only": True,
    },
    28: {
        "class_name": "hkbEventDrivenModifier",
        "xml_class": "hkbEventDrivenModifier",
        "category": "hkbE",
        "signature": "0x35ef356b",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "activateEventId": ("int", -1),
            "deactivateEventId": ("int", -1),
            "activeByDefault": ("bool", False),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("modifier", False),
        ],
        "input_ports": [("in", False)],
    },
    29: {
        "class_name": "hkbPoweredRagdollControlsModifier",
        "xml_class": "hkbPoweredRagdollControlsModifier",
        "category": "hkbP",
        "signature": "0x522211cb",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "maxForce": ("str", "50.000000"),
            "tau": ("str", "0.800000"),
            "damping": ("str", "1.000000"),
            "proportionalRecoveryVelocity": ("str", "2.000000"),
            "constantRecoveryVelocity": ("str", "1.000000"),
            "poseMatchingBone0": ("int", -1),
            "poseMatchingBone1": ("int", -1),
            "poseMatchingBone2": ("int", -1),
            "mode": ("int", 0),
            "animationBlendFraction": ("str", "0.000000"),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("bones", False),
        ],
        "input_ports": [("in", False)],
    },
    30: {
        "class_name": "hkbTimerModifier",
        "xml_class": "hkbTimerModifier",
        "category": "hkbT",
        "signature": "0x7880c5e2",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "alarmTimeSeconds": ("str", "0.000000"),
            "eventId": ("int", -1),
            "payload": ("int", -1),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
    },
    31: {
        "class_name": "BSLookAtModifier",
        "xml_class": "BSLookAtModifier",
        "category": "BS",
        "signature": "0x0",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
        "unsupported": True,
    },
    32: {
        "class_name": "BSGetTimeStepModifier",
        "xml_class": "BSGetTimeStepModifier",
        "category": "BS",
        "signature": "0x56341150",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "timeStep": ("str", "0.000000"),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
    },
    33: {
        "class_name": "hkbTwistModifier",
        "xml_class": "hkbTwistModifier",
        "category": "hkbT",
        "signature": "0x98d623bc",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "axisOfRotation": ("str", "(0.0 0.0 1.0 0.0)"),
            "twistAngle": ("str", "0.000000"),
            "startBoneIndex": ("int", -1),
            "endBoneIndex": ("int", -1),
            "setAngleMethod": ("int", 0),
            "rotationAxisCoordinates": ("int", 0),
            "isAdditive": ("bool", False),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
    },
    34: {
        "class_name": "BSInterpValueModifier",
        "xml_class": "BSInterpValueModifier",
        "category": "BS",
        "signature": "0x4c10e936",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "source": ("str", "0.000000"),
            "target": ("str", "0.000000"),
            "result": ("str", "0.000000"),
            "gain": ("str", "0.000000"),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
    },
    35: {
        "class_name": "hkbEventsFromRangeModifier",
        "xml_class": "hkbEventsFromRangeModifier",
        "category": "hkbE",
        "signature": "0xc9ece705",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "inputValue": ("str", "0.000000"),
            "lowerBound": ("str", "0.000000"),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("eventRanges", False),
        ],
        "input_ports": [("in", False)],
    },
    36: {
        "class_name": "hkbEventRangeDataArray",
        "xml_class": "hkbEventRangeDataArray",
        "category": "hkbE",
        "signature": "0x83502c2d",
        "properties": {
            "rangeArray": ("list", []),
        },
        "output_ports": [],
        "input_ports": [("in", False)],
    },
    37: {
        "class_name": "BSBehaviorGraphSwapGenerator",
        "xml_class": "BSBehaviorGraphSwapGenerator",
        "category": "BS",
        "signature": "0xe7633191",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("pDefaultGenerator", False),
        ],
        "input_ports": [("in", False)],
    },
    38: {
        "class_name": "BSRagdollContactListenerModifier",
        "xml_class": "BSRagdollContactListenerModifier",
        "category": "BS",
        "signature": "0x7e6d66c9",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "eventId": ("int", -1),
            "payload": ("int", -1),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("bones", False),
        ],
        "input_ports": [("in", False)],
    },
    39: {
        "class_name": "BSCyclicBlendTransitionGenerator",
        "xml_class": "BSCyclicBlendTransitionGenerator",
        "category": "BS",
        "signature": "0x86401931",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "EventToFreezeBlendValueID": ("int", -1),
            "EventToFreezeBlendValuePayload": ("int", -1),
            "EventToCrossBlendID": ("int", -1),
            "EventToCrossBlendPayload": ("int", -1),
            "TransitionOutEventID": ("int", -1),
            "TransitionOutEventPayload": ("int", -1),
            "TransitionInEventID": ("int", -1),
            "TransitionInEventPayload": ("int", -1),
            "fTransitionDuration": ("str", "0.000000"),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("pBlenderGenerator", False),
        ],
        "input_ports": [("in", False)],
    },
    40: {
        "class_name": "BGSGamebryoSequenceGenerator",
        "xml_class": "BGSGamebryoSequenceGenerator",
        "category": "Root",
        "signature": "0x4e708fb6",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "pSequence": ("str", ""),
            "eBlendModeFunction": ("str", "BMF_NONE"),
            "fPercent": ("str", "0.000000"),
            "eUseTimePercentage": ("str", "UST_NO"),
            "fTimePercent": ("str", "0.000000"),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
    },
    41: {
        "class_name": "hkbStringEventPayload",
        "xml_class": "hkbStringEventPayload",
        "category": "Metadata",
        "signature": "0xdf5fe694",
        "properties": {},
        "output_ports": [],
        "input_ports": [],
        "metadata_only": True,
    },
    42: {
        "class_name": "hkbBehaviorReferenceGenerator",
        "xml_class": "hkbBehaviorReferenceGenerator",
        "category": "hkbB",
        "signature": "0x154fcfaa",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "behaviorName": ("str", ""),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
    },
    43: {
        "class_name": "BSAssignVariablesModifier",
        "xml_class": "BSAssignVariablesModifier",
        "category": "BS",
        "signature": "0x64a6ca08",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "floatVariable": ("list", ["0"] * 20),
            "floatValue": ("list", ["0"] * 20),
            "intVariable": ("list", [0] * 4),
            "intValue": ("list", [0] * 4),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
    },
    44: {
        "class_name": "DynamicAnimationTaggingGenerator",
        "xml_class": "DynamicAnimationTaggingGenerator",
        "category": "Root",
        "signature": "0xe7633191",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("pDefaultGenerator", False),
        ],
        "input_ports": [("in", False)],
    },
    45: {
        "class_name": "BSTimerModifier",
        "xml_class": "BSTimerModifier",
        "category": "BS",
        "signature": "0x9266ffac",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "alarmTimeSeconds": ("str", "0.000000"),
            "eventId": ("int", -1),
            "payload": ("int", -1),
            "resetAlarm": ("bool", False),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
    },
    46: {
        "class_name": "BSiStateTaggingGenerator",
        "xml_class": "BSiStateTaggingGenerator",
        "category": "BS",
        "signature": "0xc932a82a",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "iStateToSetAs": ("int", 0),
            "iPriority": ("int", 0),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("pDefaultGenerator", False),
        ],
        "input_ports": [("in", False)],
    },
    47: {
        "class_name": "hkbGeneratorTransitionEffect",
        "xml_class": "hkbGeneratorTransitionEffect",
        "category": "hkbG",
        "signature": "0x44208f07",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "selfTransitionMode": ("int", 0),
            "eventMode": ("int", 0),
            "blendInDuration": ("str", "0.000000"),
            "blendOutDuration": ("str", "0.000000"),
            "syncToGeneratorStartTime": ("bool", False),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("transitionGenerator", False),
        ],
        "input_ports": [("in", False)],
    },
    48: {
        "class_name": "hkbReferencePoseGenerator",
        "xml_class": "hkbReferencePoseGenerator",
        "category": "hkbR",
        "signature": "0xbc1536ee",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
    },
    49: {
        "class_name": "hkbDampingModifier",
        "xml_class": "hkbDampingModifier",
        "category": "Root",
        "signature": "0x68a51d05",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "kP": ("str", "1.000000"),
            "kI": ("str", "0.000000"),
            "kD": ("str", "0.000000"),
            "enableScalarDamping": ("bool", False),
            "enableVectorDamping": ("bool", False),
            "rawValue": ("str", "0.000000"),
            "dampedValue": ("str", "0.000000"),
            "rawVector": ("str", "(0.0 0.0 0.0 0.0)"),
            "dampedVector": ("str", "(0.0 0.0 0.0 0.0)"),
            "vecErrorSum": ("str", "(0.0 0.0 0.0 0.0)"),
            "vecPreviousError": ("str", "(0.0 0.0 0.0 0.0)"),
            "errorSum": ("str", "0.000000"),
            "previousError": ("str", "0.000000"),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
    },
    50: {
        "class_name": "hkbLayer",
        "xml_class": "hkbLayer",
        "category": "hkbL",
        "signature": "0x2916a243",
        "properties": {
            "weight": ("str", "1.000000"),
            "worldFromModelWeight": ("str", "1.000000"),
            "fadeInDuration": ("str", "0.000000"),
            "fadeOutDuration": ("str", "0.000000"),
            "onEventId": ("int", -1),
            "offEventId": ("int", -1),
            "onByDefault": ("bool", True),
            "useMotion": ("bool", False),
            "forceFullFadeDurations": ("bool", False),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("generator", False),
            ("boneWeights", False),
        ],
        "input_ports": [("in", False)],
    },
    51: {
        "class_name": "hkbLayerGenerator",
        "xml_class": "hkbLayerGenerator",
        "category": "hkbL",
        "signature": "0xb4e0c52f",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "indexOfSyncMasterChild": ("int", 65535),
            "flagsIndex": ("int", 0),
        },
        "output_ports": [
            ("variableBindingSet", False),
            ("layers", True),
        ],
        "input_ports": [("in", False)],
    },
    52: {
        "class_name": "BSDirectAtModifier",
        "xml_class": "BSDirectAtModifier",
        "category": "BS",
        "signature": "0xcda56038",
        "properties": {
            "nodeName": ("str", ""),
            "userData": ("int", 0),
            "enable": ("bool", True),
            "directAtOn": ("bool", True),
            "target": ("str", "AppSupplied"),
            "context": ("str", "GunAttack"),
            "sourceBoneIndex": ("int", 0),
            "offsetsCharacterRelative": ("bool", True),
            "startBoneIndex": ("int", 1),
            "endBoneIndex": ("int", 2),
            "limitHeadingDegreesCCW": ("str", "90.000000"),
            "limitHeadingDegreesCW": ("str", "90.000000"),
            "limitPitchDegreesUp": ("str", "0.000000"),
            "limitPitchDegreesDown": ("str", "0.000000"),
            "onGain": ("str", "0.050000"),
            "offGain": ("str", "0.050000"),
            "onLeadIn": ("str", "1.000000"),
            "offLeadIn": ("str", "1.000000"),
            "initialHeadingOffset": ("str", "0.000000"),
            "initialPitchOffset": ("str", "0.000000"),
            "initialGain": ("str", "0.000000"),
            "allowSourceBonePoseCapture": ("bool", True),
            "sourceBonePoseCaptureBlendGain": ("str", "0.050000"),
            "useCurrentSourceBonePoseEventId": ("int", -1),
            "counteractSourceBoneWorldSpaceDelta": ("bool", False),
            "snapToTargetEventId": ("int", -1),
            "directAtCameraX": ("str", "0.000000"),
            "directAtCameraY": ("str", "0.000000"),
            "directAtCameraZ": ("str", "0.000000"),
            "drawDebugInfo": ("bool", False),
            "active": ("bool", False),
            "currentHeadingOffset": ("str", "0.000000"),
            "currentPitchOffset": ("str", "0.000000"),
            "currentGain": ("str", "0.000000"),
        },
        "output_ports": [("variableBindingSet", False)],
        "input_ports": [("in", False)],
    },
}


# Reverse lookup: XML class name -> nodeTypeID
XML_CLASS_TO_TYPE_ID = {
    defn["xml_class"]: type_id
    for type_id, defn in NODE_TYPE_DEFINITIONS.items()
}

# Category groupings for the palette
CATEGORY_ORDER = [
    "Root", "hkbB", "hkbC", "hkbE", "hkbG", "hkbL",
    "hkbM", "hkbP", "hkbR", "hkbS", "hkbT", "BS",
]

CATEGORY_LABELS = {
    "Root": "Root / Misc",
    "hkbB": "hkbB* (Blender, Bone, Reference)",
    "hkbC": "hkbC* (Clip)",
    "hkbE": "hkbE* (Expression, Event)",
    "hkbG": "hkbG* (Generator, GetUp)",
    "hkbL": "hkbL* (Layer)",
    "hkbM": "hkbM* (Modifier, Manual)",
    "hkbP": "hkbP* (Pose, Powered)",
    "hkbR": "hkbR* (Reference, Ragdoll)",
    "hkbS": "hkbS* (StateMachine)",
    "hkbT": "hkbT* (Timer, Twist)",
    "BS": "BS* (Bethesda)",
}
